# Generated by Django 5.0.1 on 2025-06-10 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('company_size', models.CharField(help_text='Number of employees', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enterprise Request',
                'verbose_name_plural': 'Enterprise Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
